### ISSUE TITLE
Eufy RoboVac G10 Hybrid

### ISSUE THREAD

**Issue by Wetalya** [pbulteel/eufy_vacuum#15]
Hi!
this integration with the vacuum cleaner(Eufy RoboVac G10 Hybrid) does not work.
Could you improve support for this device?
![Screenshot_20220124_231300](https://user-images.githubusercontent.com/20833318/150857359-d567df24-89a3-4596-8d5a-18c37dd07249.jpg)

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/eufy_vacuum/property.py:36
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 23:17:26 (1 occurrences)
Last logged: 23:17:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 734, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 297, in state_attributes
    data = super().state_attributes
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 190, in state_attributes
    data[ATTR_BATTERY_ICON] = self.battery_icon
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 287, in battery_icon
    if self.status is not None:
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 116, in status
    if self.robovac.error_code != robovac.ErrorCode.NO_ERROR:
  File "/config/custom_components/eufy_vacuum/property.py", line 36, in __get__
    value = self.type_cast(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 0 is not a valid ErrorCode

**Comment by Wetalya** [comment]
+1
```
Logger: homeassistant
Source: runner.py:98
First occurred: 18:16:16 (1 occurrences)
Last logged: 18:16:16

Error doing job: Unclosed client session
```

+1
```
Logger: homeassistant
Source: custom_components/eufy_vacuum/tuya.py:551
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 04:30:19 (2 occurrences)
Last logged: 16:31:25

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/tuya.py", line 551, in _async_handle_message
    response_data = await self.reader.readuntil(MAGIC_SUFFIX_BYTES)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 629, in readuntil
    raise exceptions.IncompleteReadError(chunk, None)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of undefined expected bytes
```

+1
```
Logger: homeassistant.helpers.entity
Source: custom_components/eufy_vacuum/tuya.py:482
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 04:31:10 (1 occurrences)
Last logged: 04:31:10

Update for vacuum.robovac fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 75, in async_update
    await self.robovac.async_get()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 506, in async_get
    return await message.async_send(self, callback)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 352, in async_send
    await device._async_send(self)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 571, in _async_send
    await self.async_connect()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 482, in async_connect
    sock.connect((self.host, self.port))
OSError: [Errno 113] Host is unreachable
```

+1
```
Logger: homeassistant.helpers.entity
Source: custom_components/eufy_vacuum/tuya.py:484
Integration: Integration to Eufy Vacuum (documentation, issues)
First occurred: 04:30:37 (2 occurrences)
Last logged: 04:30:57

Update for vacuum.robovac fails
Traceback (most recent call last):
  File "/config/custom_components/eufy_vacuum/tuya.py", line 482, in async_connect
    sock.connect((self.host, self.port))
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/eufy_vacuum/vacuum.py", line 75, in async_update
    await self.robovac.async_get()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 506, in async_get
    return await message.async_send(self, callback)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 352, in async_send
    await device._async_send(self)
  File "/config/custom_components/eufy_vacuum/tuya.py", line 571, in _async_send
    await self.async_connect()
  File "/config/custom_components/eufy_vacuum/tuya.py", line 484, in async_connect
    raise ConnectionTimeoutException("Connection timed out") from e
custom_components.eufy_vacuum.tuya.ConnectionTimeoutException: Connection timed out
```
